// SPDX-License-Identifier: Apache-2.0

import {
  mkdtemp,
  readFile,
  realpath,
  rm,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import type { EvidenceRepository } from "@jinn-network/evidence-repository";
import { InMemoryEvidenceRepository } from "@jinn-network/evidence-repository/testing";

import { createExecutionRecorder } from "./recorder.js";
import {
  describeExecutionProducerContract,
  type ExecutionProducerContractDriver,
  type ExecutionProducerContractFinalizationInterruption,
  type ExecutionProducerContractFinalizedObservation,
  type ExecutionProducerContractFinalizedScenario,
  type ExecutionProducerContractScenario,
  type InterruptedFinalizationExecutionProducerContractObservation,
} from "./testing.js";
import type {
  ExecutionId,
  ExecutionRecording,
  FileArtifactCapture,
  FinalizedExecutionReceipt,
  NativeTraceCapture,
  StartExecutionRecordingInput,
} from "./types.js";

const CAPTURE_STARTED_AT = "2026-07-24T09:59:59.900Z";
const EXECUTOR_STARTED_AT = "2026-07-24T10:00:00Z";
const ENDED_AT = "2026-07-24T10:00:01Z";
const PRODUCER_ID = "https://producer.example/contract-driver";
const ORIGIN = {
  kind: "producer-observed",
  observer: PRODUCER_ID,
} as const;
const fixtureUrl = (name: string) =>
  new URL(`../fixtures/producer-contract-v1/${name}`, import.meta.url);

const EXECUTION_IDS = {
  completed: "urn:uuid:11111111-1111-4111-8111-111111111111",
  failed: "urn:uuid:22222222-2222-4222-8222-222222222222",
  abandoned: "urn:uuid:33333333-3333-4333-8333-333333333333",
  "interrupted-finalization":
    "urn:uuid:44444444-4444-4444-8444-444444444444",
} as const satisfies Record<
  ExecutionProducerContractScenario,
  ExecutionId
>;

interface ProducerContractFixtures {
  readonly task: Uint8Array;
  readonly trace: Uint8Array;
  readonly result: Uint8Array;
  readonly runtime: Uint8Array;
  readonly runner: Uint8Array;
}

interface ScenarioContext {
  readonly executionId: ExecutionId;
  readonly workspaceDir: string;
  readonly repository: EvidenceRepository;
  readonly recording: ExecutionRecording;
  readonly cleanup: () => Promise<void>;
}

interface InterruptedContext {
  readonly context: ScenarioContext;
}

async function loadFixtures(): Promise<ProducerContractFixtures> {
  const [task, trace, result, runtime, runner] = await Promise.all([
    readFile(fixtureUrl("task.md")),
    readFile(fixtureUrl("trace.jsonl")),
    readFile(fixtureUrl("result.txt")),
    readFile(fixtureUrl("runtime.json")),
    readFile(fixtureUrl("runner.mjs")),
  ]);
  return { task, trace, result, runtime, runner };
}

function file(
  entityId: string,
  bytes: Uint8Array,
  mediaType: string,
): FileArtifactCapture {
  return {
    kind: "file",
    entityId,
    source: {
      bytes,
      mediaType,
      name: entityId,
    },
    origin: ORIGIN,
  };
}

function nativeTrace(
  fixtures: ProducerContractFixtures,
): NativeTraceCapture {
  return {
    artifact: file(
      "trace.jsonl",
      fixtures.trace,
      "application/x-ndjson",
    ),
    format: {
      entityId: "https://example.test/formats/producer-contract-v1",
      name: "Producer contract native trace",
    },
  };
}

function startInput(
  workspaceDir: string,
  executionId: ExecutionId,
  scenario: string,
  fixtures: ProducerContractFixtures,
): StartExecutionRecordingInput {
  return {
    workspaceDir,
    executionId,
    startedAt: EXECUTOR_STARTED_AT,
    record: {
      name: `Real producer contract ${scenario}`,
      description:
        "Execution Evidence generated by the real execution recorder.",
      license: "https://creativecommons.org/publicdomain/zero/1.0/",
    },
    task: {
      entityId: "task.md",
      name: "Producer contract task",
      source: {
        bytes: fixtures.task,
        mediaType: "text/markdown",
        name: "task.md",
      },
      origin: ORIGIN,
    },
    executor: {
      entityId: "https://executor.example/contract-driver",
      kind: "software",
      name: "Producer contract executor",
      softwareVersion: "1.0.0",
      origin: ORIGIN,
    },
    runtime: {
      entityId: "runtime.json",
      specification: {
        bytes: fixtures.runtime,
        mediaType: "application/json",
        name: "runtime.json",
      },
      name: "Producer contract runtime",
      softwareVersion: "1.0.0",
      origin: ORIGIN,
      components: [
        {
          kind: "controlled",
          artifact: file(
            "runner.mjs",
            fixtures.runner,
            "text/javascript",
          ),
        },
      ],
    },
    producer: {
      entityId: PRODUCER_ID,
      kind: "software",
      name: "Real execution-recorder contract driver",
      softwareVersion: "1.0.0",
      origin: ORIGIN,
    },
  };
}

async function createScenarioContext(
  scenario: keyof typeof EXECUTION_IDS,
  fixtures: ProducerContractFixtures,
  repository: EvidenceRepository,
): Promise<ScenarioContext> {
  const parent = await realpath(
    await mkdtemp(
      join(tmpdir(), `jinn-producer-contract-${scenario}-`),
    ),
  );
  const workspaceDir = join(parent, "recording");
  let cleaned = false;
  const cleanup = async (): Promise<void> => {
    if (cleaned) return;
    cleaned = true;
    await rm(parent, { recursive: true, force: true });
  };

  try {
    const recording = await createExecutionRecorder({
      repository,
    }).start(
      startInput(
        workspaceDir,
        EXECUTION_IDS[scenario],
        scenario,
        fixtures,
      ),
    );
    return {
      executionId: recording.executionId,
      workspaceDir,
      repository,
      recording,
      cleanup,
    };
  } catch (error) {
    await cleanup();
    throw error;
  }
}

function receiptFrom(recording: ExecutionRecording): FinalizedExecutionReceipt {
  if (recording.status !== "finalized" || recording.receipt === undefined) {
    throw new Error("Real producer contract scenario did not finalize.");
  }
  return recording.receipt;
}

function commonObservation(
  context: ScenarioContext,
  fixtures: ProducerContractFixtures,
): {
  readonly executionId: ExecutionId;
  readonly workspaceDir: string;
  readonly captureStartedAt: string;
  readonly executorStartedAt: string;
  readonly expectedTaskBytes: Uint8Array;
  readonly expectedTraceBytes: Uint8Array;
  readonly repository: EvidenceRepository;
  readonly receipt: FinalizedExecutionReceipt;
  readonly cleanup: () => Promise<void>;
} {
  return {
    executionId: context.executionId,
    workspaceDir: context.workspaceDir,
    captureStartedAt: CAPTURE_STARTED_AT,
    executorStartedAt: EXECUTOR_STARTED_AT,
    expectedTaskBytes: fixtures.task,
    expectedTraceBytes: fixtures.trace,
    repository: context.repository,
    receipt: receiptFrom(context.recording),
    cleanup: context.cleanup,
  };
}

async function finalizeScenario(
  scenario: ExecutionProducerContractFinalizedScenario,
  fixtures: ProducerContractFixtures,
): Promise<ExecutionProducerContractFinalizedObservation> {
  const context = await createScenarioContext(
    scenario,
    fixtures,
    new InMemoryEvidenceRepository(),
  );
  try {
    const result = await context.recording.finalize({
      outcome: scenario,
      endedAt: ENDED_AT,
      ...(scenario === "completed"
        ? {
            results: [
              file("result.txt", fixtures.result, "text/plain"),
            ],
          }
        : {}),
      nativeTrace: nativeTrace(fixtures),
    });
    if (!result.finalized) {
      throw new Error(
        `Real producer contract scenario was incomplete: ${JSON.stringify(
          result.diagnostics,
        )}`,
      );
    }

    const common = commonObservation(context, fixtures);
    return scenario === "completed"
      ? {
          ...common,
          scenario,
          expectedResultBytes: fixtures.result,
        }
      : {
          ...common,
          scenario,
        };
  } catch (error) {
    await context.cleanup();
    throw error;
  }
}

async function realExecutionRecorderDriver(): Promise<ExecutionProducerContractDriver> {
  const fixtures = await loadFixtures();
  let interrupted: InterruptedContext | undefined;

  return {
    run: (scenario) => finalizeScenario(scenario, fixtures),

    async runUntilFinalizationInterrupted(
      interruptFinalization: ExecutionProducerContractFinalizationInterruption,
    ): Promise<never> {
      const backing = new InMemoryEvidenceRepository();
      let pendingInterruption:
        | ExecutionProducerContractFinalizationInterruption
        | undefined = interruptFinalization;
      const repository: EvidenceRepository = {
        putArtifact: (...args) => backing.putArtifact(...args),
        getArtifact: (...args) => backing.getArtifact(...args),
        getRecord: (...args) => backing.getRecord(...args),
        putRecord: (...args) => {
          const interrupt = pendingInterruption;
          pendingInterruption = undefined;
          if (interrupt !== undefined) return interrupt();
          return backing.putRecord(...args);
        },
      };
      const context = await createScenarioContext(
        "interrupted-finalization",
        fixtures,
        repository,
      );
      interrupted = { context };

      try {
        const result = await context.recording.finalize({
          outcome: "completed",
          endedAt: ENDED_AT,
          results: [
            file("result.txt", fixtures.result, "text/plain"),
          ],
          nativeTrace: nativeTrace(fixtures),
        });
        await context.cleanup();
        interrupted = undefined;
        throw new Error(
          `Injected finalization interruption was not observed: ${JSON.stringify(
            result,
          )}`,
        );
      } catch (error) {
        if (pendingInterruption === undefined) throw error;
        await context.cleanup();
        interrupted = undefined;
        throw error;
      }
    },

    async recoverFinalization(): Promise<InterruptedFinalizationExecutionProducerContractObservation> {
      if (interrupted === undefined) {
        throw new Error("No interrupted finalization is available to recover.");
      }
      const { context } = interrupted;
      try {
        const recording = await createExecutionRecorder({
          repository: context.repository,
        }).resume({ workspaceDir: context.workspaceDir });
        const recoveredContext = {
          ...context,
          recording,
        };
        interrupted = undefined;
        return {
          ...commonObservation(recoveredContext, fixtures),
          scenario: "interrupted-finalization",
          expectedResultBytes: fixtures.result,
        };
      } catch (error) {
        await context.cleanup();
        interrupted = undefined;
        throw error;
      }
    },
  };
}

describeExecutionProducerContract(realExecutionRecorderDriver);
