import { mkdir, readFile, writeFile } from "node:fs/promises";

import { createEoaTestSigner } from "@jinn-network/trust-testing";
import { dssePreAuthEncoding } from "@jinn-network/trust-core";

import {
  CHAIN_CONFORMANCE_SCENARIOS,
  runArchiveObservedGolden,
  runConformanceScenario,
} from "../dist/testing.js";

const eoa = createEoaTestSigner("chain-environment-verification-conformance");
const signer = async (request) => [{
  keyid: eoa.address,
  signature: eoa.sign(request.preAuthEncoding
    ?? dssePreAuthEncoding(request.payloadType, request.payloadBytes)),
}];

await mkdir("fixtures/attestations-v1", { recursive: true });
await mkdir("fixtures/predicate-v1", { recursive: true });

for (const scenario of CHAIN_CONFORMANCE_SCENARIOS) {
  const { statement } = await runConformanceScenario(scenario, signer);
  await writeFile(
    `fixtures/attestations-v1/${scenario}.json`,
    `${JSON.stringify(statement, null, 2)}\n`,
    "utf8",
  );
}

const sealedStable = JSON.parse(
  await readFile("fixtures/attestations-v1/sealed-stable.json", "utf8"),
);
await writeFile(
  "fixtures/predicate-v1/closed-reproducible.json",
  `${JSON.stringify(sealedStable.predicate, null, 2)}\n`,
  "utf8",
);

const archivePredicate = await runArchiveObservedGolden(signer);
await writeFile(
  "fixtures/predicate-v1/archive-observed.json",
  `${JSON.stringify(archivePredicate, null, 2)}\n`,
  "utf8",
);

const closed = sealedStable.predicate;

const invalidPrefixed = structuredClone(closed);
invalidPrefixed.baseline.observation.digest.sha256 =
  `sha256:${invalidPrefixed.baseline.observation.digest.sha256}`;

const invalidRunsOnNonRunBearing = structuredClone(closed);
invalidRunsOnNonRunBearing.outcome = "artifact-unavailable";
invalidRunsOnNonRunBearing.runs = closed.runs;
delete invalidRunsOnNonRunBearing.baseline;

const invalidClosedDivergent = structuredClone(closed);
invalidClosedDivergent.runs.perRun[2].observationDigest =
  `sha256:${"d".repeat(64)}`;

const invalidKBelow = structuredClone(closed);
invalidKBelow.runs.count = 4;
invalidKBelow.runs.perRun = invalidKBelow.runs.perRun.slice(0, 4);

const invalidSealedNoProbe = structuredClone(closed);
delete invalidSealedNoProbe.isolation.boundaryProbe;

const invalidReasonMismatch = structuredClone(closed);
invalidReasonMismatch.outcome = "capability-mismatch";
invalidReasonMismatch.failure = {
  stage: "resolve",
  reason: "artifact-entry-uncovered",
  detail: "forged mismatch fixture",
};

const invalidCoverageReproducible = structuredClone(
  JSON.parse(await readFile("fixtures/attestations-v1/coverage-incomplete.json", "utf8")).predicate,
);
invalidCoverageReproducible.outcome = "closed-reproducible";
delete invalidCoverageReproducible.failure;

const invalidFixtures = [
  ["invalid-prefixed-digest-set.json", invalidPrefixed],
  ["invalid-runs-on-non-run-bearing.json", invalidRunsOnNonRunBearing],
  ["invalid-closed-with-divergent-per-run.json", invalidClosedDivergent],
  ["invalid-k-below-minimum.json", invalidKBelow],
  ["invalid-sealed-without-boundary-probe.json", invalidSealedNoProbe],
  ["invalid-reason-outcome-mismatch.json", invalidReasonMismatch],
  ["invalid-coverage-uncovered-but-reproducible.json", invalidCoverageReproducible],
];

for (const [name, fixture] of invalidFixtures) {
  await writeFile(
    `fixtures/predicate-v1/${name}`,
    `${JSON.stringify(fixture, null, 2)}\n`,
    "utf8",
  );
}

await writeFile(
  "fixtures/attestations-v1/README.md",
  `# Golden chain verification attestations

Generated by the kit against the fake chain runtime and frozen. Regenerating them is allowed
only when the design changes; a diff here is a claim change, and reviewers read it as one. The
DSSE envelope is deliberately not pinned: envelope bytes depend on the signer, and the kit is
parameterized on the host's signer.
`,
  "utf8",
);

console.log("goldens written");
