// SPDX-License-Identifier: Apache-2.0

/**
 * A real local-Anvil task lifecycle for public-repository v2 rows.  The
 * evaluator is deliberately a synthetic parser-contract evaluator: it proves
 * transport, binding, delivery, settlement, and corpus projection without
 * pretending that a Docker/real-repository empirical run happened here.
 */

import {
  createPublicClient,
  http,
  keccak256,
  parseEther,
  toBytes,
  type Hex,
  type PublicClient,
} from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { base } from 'viem/chains';
import { projectEnvelope } from '../../src/corpus/envelope-projection.js';
import { computeMintedPoolRowV2Hash, type MintedPoolRowV2 } from '../../src/solver-types/_swe-rebench-v2-minted-pool.js';
import { commandSpecToEvaluatorCommand } from '../../src/solver-types/_swe-rebench-v2-harvest.js';
import {
  bindJinnDifferentialReceiptToProof,
  type BindJinnDifferentialReceiptToProofInput,
  type ReceiptBoundJinnDifferentialProof,
} from '../../src/task-creator/proofs/differential-receipt-bound-proof.js';
import type { PublicRepoProofFixture } from '../../src/task-creator/proofs/public-repo-fixtures.js';
import { runPublicRepoParityFixture } from '../../src/task-creator/proofs/vitest-json-fixture.js';
import { resolveJinnMonoRecipeV1 } from '../../src/task-creator/environment/recipes.js';
import {
  ANVIL_PRIVATE_KEYS,
  assert,
  compileContracts,
  decodeFirstEvent,
  deployTaskFirstStack,
  signedExecutionEnvelope,
  spawnPlainAnvil,
  tupleField,
  writeContractTx,
} from '../e2e/task-first-helpers.js';
import { jsonRpc as anvilJsonRpc } from '../_support/chain/anvil.js';

export type PublicRepoAnvilEvidence = {
  fixture: string;
  taskId: string;
  taskArtifactCid: string;
  environmentSpecCid: string;
  row: {
    instanceId: string;
    rowHashVersion: 2;
    publicRowHash: `sha256:${string}`;
    FAIL_TO_PASS: string[];
    PASS_TO_PASS: string[];
  };
  admissionReceipt: {
    kind: 'test-only-parser-contract-fixture' | 'verified-differential-admission-receipt';
    receiptCid: string;
    receiptHash: `sha256:${string}`;
  };
  solutionDelivery: { requestId: string; txHash: string };
  verdictDelivery: { requestId: string; txHash: string };
  verdict: { code: 1; source: string; passed: true };
  corpusEvidence: {
    taskArtifactCid: string;
    environmentSpecCid: string;
    receiptCid: string;
    receiptHash: `sha256:${string}`;
    publicRowHash: `sha256:${string}`;
    solutionDeliveryTxHash: string;
    verdictDeliveryTxHash: string;
    solutionProjectionId: string;
    verdictProjectionId: string;
  };
};

type PreparedPublicRepoLifecycle = {
  fixture: string;
  row: MintedPoolRowV2;
  source: 'synthetic-parser-contract' | 'test-only-differential-admission-contract-fixture';
  admissionReceipt: PublicRepoAnvilEvidence['admissionReceipt'];
};

/**
 * Runs two actual on-chain task lifecycles on one fresh Anvil stack.  No
 * network process is mocked in place of Anvil: createTask, claimTask,
 * solution delivery, evaluation claim, verdict delivery, and finalization are
 * contract transactions.  Only the test result source is synthetic.
 */
export async function runPublicRepoAnvilLifecycle(
  fixtures: readonly PublicRepoProofFixture[],
): Promise<PublicRepoAnvilEvidence[]> {
  const prepared = fixtures.map(prepareSyntheticParserContractLifecycle);
  return runPreparedPublicRepoAnvilLifecycle(prepared);
}

/**
 * Deterministic contract coverage for the real Jinn receipt shape. This is
 * not empirical proof: callers provide a test-only receipt fixture, while the
 * genuine route must use the receipt generated by the Docker proof command.
 * Binding happens before compilation, deployment, task creation, or delivery.
 */
export async function runReceiptBoundJinnAnvilContractLifecycle(
  input: BindJinnDifferentialReceiptToProofInput,
): Promise<PublicRepoAnvilEvidence> {
  const bound = await bindJinnDifferentialReceiptToProof(input);
  return runBoundJinnAnvilContractLifecycle(bound);
}

/** Run an already-verified and receipt-bound v2 row through the real local-Anvil lifecycle. */
export async function runBoundJinnAnvilContractLifecycle(
  bound: ReceiptBoundJinnDifferentialProof,
): Promise<PublicRepoAnvilEvidence> {
  const [evidence] = await runPreparedPublicRepoAnvilLifecycle([
    prepareReceiptBoundJinnContractLifecycle(bound),
  ]);
  if (!evidence) throw new Error('receipt-bound Jinn Anvil contract lifecycle produced no evidence');
  return evidence;
}

async function runPreparedPublicRepoAnvilLifecycle(
  prepared: readonly PreparedPublicRepoLifecycle[],
): Promise<PublicRepoAnvilEvidence[]> {
  await compileContracts();
  const anvil = await spawnPlainAnvil();
  const accounts = ANVIL_PRIVATE_KEYS.map((key) => privateKeyToAccount(key));
  const [creator, solver, spareOperator, evaluator] = accounts;
  assert(creator && solver && spareOperator && evaluator, 'missing deterministic Anvil lifecycle accounts');
  const publicClient = createPublicClient({ chain: base, transport: http(anvil.rpcUrl) }) as unknown as PublicClient;
  const rate = parseEther('0.01');

  try {
    for (const account of accounts) {
      await anvilJsonRpc(anvil.rpcUrl, 'anvil_setBalance', [
        account.address,
        '0x56bc75e2d63100000',
      ]);
    }
    const { deployment, artifacts } = await deployTaskFirstStack(
      publicClient,
      anvil.rpcUrl,
      creator,
      solver,
      spareOperator,
      evaluator,
      rate,
    );

    const evidence: PublicRepoAnvilEvidence[] = [];
    for (const proof of prepared) {
      evidence.push(await runFixtureLifecycle({
        proof,
        expectedTaskId: BigInt(evidence.length + 1),
        publicClient,
        rpcUrl: anvil.rpcUrl,
        creator,
        solver,
        evaluator,
        deployment,
        artifacts,
        rate,
      }));
    }
    return evidence;
  } finally {
    await anvil.teardown();
  }
}

async function runFixtureLifecycle(args: {
  proof: PreparedPublicRepoLifecycle;
  expectedTaskId: bigint;
  publicClient: PublicClient;
  rpcUrl: string;
  creator: ReturnType<typeof privateKeyToAccount>;
  solver: ReturnType<typeof privateKeyToAccount>;
  evaluator: ReturnType<typeof privateKeyToAccount>;
  deployment: Awaited<ReturnType<typeof deployTaskFirstStack>>['deployment'];
  artifacts: Awaited<ReturnType<typeof deployTaskFirstStack>>['artifacts'];
  rate: bigint;
}): Promise<PublicRepoAnvilEvidence> {
  const row = args.proof.row;
  const taskArtifactCid = `bafy-public-repo-${args.proof.fixture}-minted-pool-v2`;
  const taskDocument = {
    schemaVersion: 'task.v1',
    id: row.instance_id,
    solverType: 'swe-rebench-v2.v1',
    role: 'restoration',
    source: args.proof.source,
    differentialAdmission: args.proof.admissionReceipt,
    taskArtifactCid,
    spec: publicTaskSpec(row, args.proof.admissionReceipt),
  };
  const taskCidDigest = keccak256(toBytes(JSON.stringify(taskDocument)));
  const taskCid = `f01551220${taskCidDigest.slice(2)}`;
  const created = await writeContractTx({
    publicClient: args.publicClient,
    rpcUrl: args.rpcUrl,
    account: args.creator,
    address: args.deployment.router,
    abi: args.artifacts.router.abi,
    functionName: 'createTask',
    args: [
      taskCidDigest,
      keccak256(toBytes('swe-rebench-v2.v1')),
      { maxClaims: 1, allowSolverSelfEvaluation: false },
      args.rate,
      args.rate,
      3600n,
    ],
    value: args.rate * 2n,
  });
  const taskCreated = decodeFirstEvent(created.receipt, args.artifacts.router.abi, 'TaskCreated');
  const taskId = BigInt(String(taskCreated['taskId']));
  assert(taskId === args.expectedTaskId, `unexpected Anvil task id ${taskId}`);

  const claim = await writeContractTx({
    publicClient: args.publicClient,
    rpcUrl: args.rpcUrl,
    account: args.solver,
    address: args.deployment.router,
    abi: args.artifacts.router.abi,
    functionName: 'claimTask',
    args: [taskId, args.deployment.mechA],
  });
  const attempt = decodeFirstEvent(claim.receipt, args.artifacts.router.abi, 'TaskAttemptCreated');
  const solutionRequestId = String(attempt['requestId']);
  assert(Number(attempt['attemptIndex']) === 0, 'first public-repository attempt must be index zero');

  const now = Date.now();
  const solutionEnvelope = await signedExecutionEnvelope({
    solverType: 'swe-rebench-v2.v1',
    role: 'solution',
    taskCid,
    requestId: solutionRequestId,
    onchainCreationTx: created.hash,
    onchainCreationBlock: Number(created.receipt.blockNumber),
    safeAddress: args.solver.address,
    privateKey: ANVIL_PRIVATE_KEYS[1],
    window: { startTs: now - 5_000, endTs: now + 3_600_000 },
    implName: `public-repo-${args.proof.source}-solver`,
    payload: {
      schemaVersion: 'swe-rebench-v2.solution.v1',
      instance_id: row.instance_id,
      patch: 'synthetic-local-solution; no gold material',
      publicRowHash: row.publicRowHash,
      differentialAdmission: args.proof.admissionReceipt,
    },
  });
  const solutionDelivery = await deliverSolution({
    publicClient: args.publicClient,
    rpcUrl: args.rpcUrl,
    account: args.solver,
    mech: args.deployment.mechA,
    router: args.deployment.router,
    mechAbi: args.artifacts.mech.abi,
    routerAbi: args.artifacts.router.abi,
    requestId: solutionRequestId,
    deliveryHash: solutionEnvelope.signature.hash,
  });

  const evaluation = await writeContractTx({
    publicClient: args.publicClient,
    rpcUrl: args.rpcUrl,
    account: args.evaluator,
    address: args.deployment.router,
    abi: args.artifacts.router.abi,
    functionName: 'claimEvaluation',
    args: [taskId, 0, args.deployment.mechEvaluator, keccak256(toBytes(`evaluation:${taskCid}:${solutionRequestId}`))],
  });
  const evaluationAttempt = decodeFirstEvent(evaluation.receipt, args.artifacts.router.abi, 'EvaluationAttemptCreated');
  const verdictRequestId = String(evaluationAttempt['requestId']);
  assert(Number(evaluationAttempt['verdictIndex']) === 0, 'first evaluator verdict must use index zero');

  const verdictEnvelope = await signedExecutionEnvelope({
    solverType: 'swe-rebench-v2.v1',
    role: 'verdict',
    taskCid,
    requestId: verdictRequestId,
    onchainCreationTx: created.hash,
    onchainCreationBlock: Number(created.receipt.blockNumber),
    safeAddress: args.evaluator.address,
    privateKey: ANVIL_PRIVATE_KEYS[3],
    window: { startTs: now - 5_000, endTs: now + 3_600_000 },
    implName: `public-repo-${args.proof.source}-evaluator`,
    payload: {
      schemaVersion: 'swe-rebench-v2.verdict.v1',
      instance_id: row.instance_id,
      verdict: 'PASS',
      source: args.proof.source,
      publicRowHash: row.publicRowHash,
      parser: row.environment.parser,
      differentialAdmission: args.proof.admissionReceipt,
    },
  });
  const verdictDelivery = await deliverVerdict({
    publicClient: args.publicClient,
    rpcUrl: args.rpcUrl,
    account: args.evaluator,
    mech: args.deployment.mechEvaluator,
    router: args.deployment.router,
    mechAbi: args.artifacts.mech.abi,
    routerAbi: args.artifacts.router.abi,
    requestId: verdictRequestId,
    deliveryHash: verdictEnvelope.signature.hash,
  });

  const attemptRecord = await args.publicClient.readContract({
    address: args.deployment.coordinator,
    abi: args.artifacts.coordinator.abi,
    functionName: 'getAttempt',
    args: [taskId, 0],
  });
  assert(tupleField<string>(attemptRecord, 'requestId', 3).toLowerCase() === solutionRequestId.toLowerCase(), 'solution request did not bind to task attempt');
  assert(tupleField<string>(attemptRecord, 'solutionCidDigest', 4).toLowerCase() === solutionEnvelope.signature.hash.toLowerCase(), 'solution delivery evidence hash drifted');
  // Current tokenless coordinator finalizes an attempt after the first verdict;
  // the AttemptRecord ABI ends at `status` (index 7), and `Finalized` is 4.
  assert(Number(tupleField<bigint>(attemptRecord, 'status', 7)) === 4, 'attempt did not finalize after its verdict');

  const solutionProjection = projectEnvelope(solutionEnvelope, {
    envelopeCid: `bafy-public-repo-${args.proof.fixture}-solution`,
    taskCid,
    taskId: String(taskId),
    metadata: {
      'taskArtifact.cid': taskArtifactCid,
      'environment.cid': row.environment.environmentSpecCid,
      'differentialAdmission.cid': args.proof.admissionReceipt.receiptCid,
      'differentialAdmission.hash': args.proof.admissionReceipt.receiptHash,
      'publicRowHash': row.publicRowHash,
      'delivery.txHash': solutionDelivery.txHash,
    },
  });
  const verdictProjection = projectEnvelope(verdictEnvelope, {
    envelopeCid: `bafy-public-repo-${args.proof.fixture}-verdict`,
    taskCid,
    taskId: String(taskId),
    metadata: {
      'taskArtifact.cid': taskArtifactCid,
      'environment.cid': row.environment.environmentSpecCid,
      'differentialAdmission.cid': args.proof.admissionReceipt.receiptCid,
      'differentialAdmission.hash': args.proof.admissionReceipt.receiptHash,
      'publicRowHash': row.publicRowHash,
      'delivery.txHash': verdictDelivery.txHash,
    },
  });
  return {
    fixture: args.proof.fixture,
    taskId: String(taskId),
    taskArtifactCid,
    environmentSpecCid: row.environment.environmentSpecCid,
    row: {
      instanceId: row.instance_id,
      rowHashVersion: row.rowHashVersion,
      publicRowHash: row.publicRowHash,
      FAIL_TO_PASS: [...row.FAIL_TO_PASS],
      PASS_TO_PASS: [...row.PASS_TO_PASS],
    },
    admissionReceipt: args.proof.admissionReceipt,
    solutionDelivery: { requestId: solutionRequestId, txHash: solutionDelivery.txHash },
    verdictDelivery: { requestId: verdictRequestId, txHash: verdictDelivery.txHash },
    verdict: { code: 1, source: args.proof.source, passed: true },
    corpusEvidence: {
      taskArtifactCid,
      environmentSpecCid: row.environment.environmentSpecCid,
      receiptCid: args.proof.admissionReceipt.receiptCid,
      receiptHash: args.proof.admissionReceipt.receiptHash,
      publicRowHash: row.publicRowHash,
      solutionDeliveryTxHash: solutionDelivery.txHash,
      verdictDeliveryTxHash: verdictDelivery.txHash,
      solutionProjectionId: solutionProjection.envelopeId,
      verdictProjectionId: verdictProjection.envelopeId,
    },
  };
}

function prepareSyntheticParserContractLifecycle(
  proof: PublicRepoProofFixture,
): PreparedPublicRepoLifecycle {
  const fixture = runPublicRepoParityFixture(proof);
  assert(fixture.verdicts.gold === true, `${proof.id} synthetic parser-contract evaluator must accept gold`);
  const row = mintedRow(fixture);
  return {
    fixture: proof.id,
    row,
    source: 'synthetic-parser-contract',
    admissionReceipt: {
      kind: 'test-only-parser-contract-fixture',
      receiptCid: `bafy-test-only-${proof.id}-parser-contract-receipt`,
      receiptHash: row.publicRowHash,
    },
  };
}

function prepareReceiptBoundJinnContractLifecycle(
  bound: ReceiptBoundJinnDifferentialProof,
): PreparedPublicRepoLifecycle {
  const recipe = resolveJinnMonoRecipeV1(bound.source.baseCommit);
  const failToPass = bound.receipt.testPaths.flatMap((path) => path.FAIL_TO_PASS);
  const passToPass = bound.receipt.testPaths.flatMap((path) => path.PASS_TO_PASS);
  const row = {
    instance_id: bound.source.instanceId,
    repo: bound.source.repo,
    base_commit: bound.source.baseCommit,
    fix_commit: bound.source.fixCommit,
    language: bound.source.language,
    problem_statement: 'Test-only receipt-bound Jinn #1422 Anvil contract coverage; not empirical proof.',
    image_name: bound.environment.image.reference,
    FAIL_TO_PASS: failToPass,
    PASS_TO_PASS: passToPass,
    test_patch: bound.testPatch,
    install_config: {
      install: recipe.installCommands.map(commandSpecToEvaluatorCommand),
      test_cmd: recipe.testCommands.map(commandSpecToEvaluatorCommand),
      log_parser: bound.environment.parser.id,
    },
    rowHashVersion: 2 as const,
    environment: bound.environment,
    differentialAdmission: {
      admissionPolicyVersion: bound.receipt.admissionPolicyVersion,
      receiptCid: bound.receiptCid,
      receiptHash: bound.receiptHash,
    },
    publicRowHash: '' as `sha256:${string}`,
  } satisfies Omit<MintedPoolRowV2, 'publicRowHash'> & { publicRowHash: `sha256:${string}` };
  const hashedRow = { ...row, publicRowHash: computeMintedPoolRowV2Hash(row) };
  return {
    fixture: 'jinn-mono-differential-admission-contract-fixture',
    row: hashedRow,
    source: 'test-only-differential-admission-contract-fixture',
    admissionReceipt: {
      kind: 'verified-differential-admission-receipt',
      receiptCid: bound.receiptCid,
      receiptHash: bound.receiptHash,
    },
  };
}

function mintedRow(fixture: ReturnType<typeof runPublicRepoParityFixture>): MintedPoolRowV2 {
  const row = {
    instance_id: fixture.proof.instanceId,
    repo: fixture.proof.repo,
    base_commit: fixture.proof.baseCommit,
    language: fixture.proof.language,
    problem_statement: fixture.proof.problemStatement,
    image_name: fixture.environment.image.reference,
    FAIL_TO_PASS: fixture.parity.FAIL_TO_PASS,
    PASS_TO_PASS: fixture.parity.PASS_TO_PASS,
    test_patch: fixture.testPatch,
    install_config: fixture.installConfig,
    rowHashVersion: 2 as const,
    environment: fixture.environment,
    publicRowHash: '' as `sha256:${string}`,
  } satisfies Omit<MintedPoolRowV2, 'publicRowHash'> & { publicRowHash: `sha256:${string}` };
  return { ...row, publicRowHash: computeMintedPoolRowV2Hash(row) };
}

function publicTaskSpec(
  row: MintedPoolRowV2,
  admissionReceipt: PublicRepoAnvilEvidence['admissionReceipt'],
): Record<string, unknown> {
  return {
    schemaVersion: 'swe-rebench-v2.v1',
    instance_id: row.instance_id,
    repo: row.repo,
    base_commit: row.base_commit,
    language: row.language,
    problem_statement: row.problem_statement,
    hf_dataset: 'ipfs://synthetic-public-repo-v2',
    hf_split: 'minted',
    rowHashVersion: row.rowHashVersion,
    publicRowHash: row.publicRowHash,
    environment: row.environment,
    differentialAdmission: admissionReceipt,
  };
}

async function deliverSolution(args: {
  publicClient: PublicClient;
  rpcUrl: string;
  account: ReturnType<typeof privateKeyToAccount>;
  mech: `0x${string}`;
  router: `0x${string}`;
  mechAbi: Awaited<ReturnType<typeof deployTaskFirstStack>>['artifacts']['mech']['abi'];
  routerAbi: Awaited<ReturnType<typeof deployTaskFirstStack>>['artifacts']['router']['abi'];
  requestId: string;
  deliveryHash: Hex;
}): Promise<{ txHash: string }> {
  await writeContractTx({
    publicClient: args.publicClient, rpcUrl: args.rpcUrl, account: args.account,
    address: args.mech, abi: args.mechAbi, functionName: 'deliverToMarketplace',
    args: [[args.requestId], [args.deliveryHash]],
  });
  const claimed = await writeContractTx({
    publicClient: args.publicClient, rpcUrl: args.rpcUrl, account: args.account,
    address: args.router, abi: args.routerAbi, functionName: 'claimSolutionDelivery',
    args: [args.requestId, args.deliveryHash],
  });
  return { txHash: claimed.hash };
}

async function deliverVerdict(args: {
  publicClient: PublicClient;
  rpcUrl: string;
  account: ReturnType<typeof privateKeyToAccount>;
  mech: `0x${string}`;
  router: `0x${string}`;
  mechAbi: Awaited<ReturnType<typeof deployTaskFirstStack>>['artifacts']['mech']['abi'];
  routerAbi: Awaited<ReturnType<typeof deployTaskFirstStack>>['artifacts']['router']['abi'];
  requestId: string;
  deliveryHash: Hex;
}): Promise<{ txHash: string }> {
  await writeContractTx({
    publicClient: args.publicClient, rpcUrl: args.rpcUrl, account: args.account,
    address: args.mech, abi: args.mechAbi, functionName: 'deliverToMarketplace',
    args: [[args.requestId], [args.deliveryHash]],
  });
  const claimed = await writeContractTx({
    publicClient: args.publicClient, rpcUrl: args.rpcUrl, account: args.account,
    address: args.router, abi: args.routerAbi, functionName: 'claimVerdictDelivery',
    args: [args.requestId, args.deliveryHash, 1],
  });
  return { txHash: claimed.hash };
}
