import { describe, expect, test } from "vitest";

import * as runtime from "./index.js";

describe("public surface", () => {
  test("exports exactly the runtime's public names", () => {
    expect(Object.keys(runtime).sort()).toEqual([
      "ARCHIVE_BUSY_ERROR_CODE",
      "BODY_TERM_WEIGHT",
      "CAPTURE_LICENSE",
      "CORPUS_ERROR_CODES",
      "CORPUS_PROJECTOR_VERSION",
      "CORPUS_SYNC_LOCK_FORMAT",
      "CorpusMirrorError",
      "DEFAULT_CORPUS_PRODUCER_PURPOSE",
      "DEFAULT_PROJECTION_MAX_CHARS",
      "DEFAULT_PROJECTION_MAX_RECORDS",
      "DEFAULT_SEARCH_LIMIT",
      "DETECTOR_FAILURE_CLASS",
      "ENVIRONMENT_KEYS",
      "EXCLUDING_BANDS",
      "FAMILY_BY_RECORD_KIND",
      "FENCE_PREFIX",
      "HIGH_WATER_MARK_FORMAT",
      "MAX_BODY_CHARS",
      "MAX_EXCERPT_CHARS",
      "MAX_INDEXED_EXCERPTS",
      "MAX_SUMMARY_CHARS",
      "MIRROR_REPOSITORY_ID",
      "PLANES",
      "PRODUCER_IRI",
      "PRODUCER_NAME",
      "PROVENANCE_PREAMBLE",
      "PluginRuntimeError",
      "QUOTE_PREFIX",
      "RELEVANCE_FLOOR",
      "RETENTION_POLICY_STATEMENT",
      "RUNTIME_ERROR_CODES",
      "RUNTIME_VERSION",
      "RuntimeConfigFileSchema",
      "SEAL_MARKER_FILENAME",
      "SENSITIVE_CLASSES",
      "SESSION_FEED_FORMAT_IRI",
      "SESSION_FEED_MEDIA_TYPE",
      "SESSION_FEED_VERSION",
      "SESSION_ID_PROPERTY",
      "STOPWORDS",
      "SUMMARY_TERM_WEIGHT",
      "TRAJECTORY_ARTIFACT_MEDIA_TYPE",
      "TRAJECTORY_BUILDER_ID",
      "TRAJECTORY_BUILDER_VERSION",
      "TRAJECTORY_RECORD_IDENTIFIER_PROPERTY",
      "TRUNCATION_TAIL",
      "UNVERIFIED_CHAIN_ACKNOWLEDGEMENT",
      "adaptAnnouncementEntry",
      "assertSafeSessionId",
      "buildFinalizeInput",
      "buildStartInput",
      "buildTrajectoryRecord",
      "buildTrajectorySpans",
      "comparePlanes",
      "composeAdmission",
      "createCaptureCapability",
      "createCorpusAdmissionFilter",
      "createCorpusCapability",
      "createCorpusFilesystem",
      "createCorpusMirror",
      "createCorpusReader",
      "createCorpusRepositoryResolver",
      "createCorpusRetrieval",
      "createDeniedProducerAdmission",
      "createDriverChainVerification",
      "createFileHighWaterMarkStore",
      "createFollowedSourceAdmission",
      "createLineLogger",
      "createMirroringRepository",
      "createPluginRuntime",
      "createRejectingChainVerification",
      "createSensitivityClassifier",
      "createServingPlaneRepository",
      "createSilentLogger",
      "createTraceSpanSource",
      "createTrustPolicyAdmission",
      "createUnverifiedChainVerification",
      "derivationLinkPath",
      "deriveFence",
      "deriveRepositorySearchTerms",
      "deriveSearchTerms",
      "discriminatingTerms",
      "ensureOwnerOnlyDirectory",
      "ensureOwnerOnlyFile",
      "executorIri",
      "indexLocalPlane",
      "indexLocalRecord",
      "indexPublicPlane",
      "listStrandedSessionIds",
      "loadTrajectoryDerivationAttestation",
      "loadTrajectoryRecord",
      "openCorpusMirrorStore",
      "openRelevanceIndex",
      "parseSessionFeed",
      "producerIdOf",
      "projectContext",
      "quoteBlock",
      "readRetentionWatermark",
      "readTrajectoryDerivationAttestationLink",
      "rebuildIndex",
      "renderFencedBlock",
      "resolveCapturePaths",
      "resolveRuntimeConfig",
      "resolveSessionOutcome",
      "runPickup",
      "sessionDirectory",
      "sessionFeedPath",
      "sessionSummary",
      "sourceIdOf",
      "summarizeHealth",
      "sweepCaptureRetention",
      "trajectoryReferenceFromRecordBytes",
      "truncateLineBoundary",
      "tryAcquireSyncLock",
      "withCaptureArchive",
      "withCorpusMirrorStore",
      "workspaceDirectory",
      "writeTrajectoryDerivationAttestationLink",
    ]);
  });

  test("does not export the binary's entry point", () => {
    expect("main" in runtime).toBe(false);
    expect("BinIo" in runtime).toBe(false);
  });

  test("a consumer can build and run a runtime from the public surface alone", async () => {
    const config = runtime.resolveRuntimeConfig({ env: {}, homeDirectory: "/srv/consumer" });
    const instance = runtime.createPluginRuntime({ config });
    await instance.start();
    await expect(instance.health()).resolves.toEqual({
      ok: true,
      version: runtime.RUNTIME_VERSION,
      checks: [],
    });
    await instance.stop();
  });
});
