/**
 * CLI password resolution.
 *
 * Priority order for `resolveCliPassword`:
 *   1. `--password-fd N`                           (explicit, scripted/CI use)
 *   2. `JINN_PASSWORD` env var                     (explicit, operator-set)
 *   3. `<earningDir>/keystore-password`            (primary; auto-generated by `jinn run`)
 *   4. `<default state dir>/keystore-password`     (legacy host-wide fallback)
 *   5. Error
 *
 * SECURITY TRADE-OFF (known, accepted for Phase 1b testers):
 *   When `jinn run` auto-generates a password, it writes the plaintext
 *   value to `<earningDir>/keystore-password` (mode 0o600) and the encrypted
 *   keystore to `<earningDir>/master_keystore.json`. An attacker with
 *   shell access to the host can read both and decrypt the mnemonic — the
 *   encryption provides defense only against casual filesystem snooping,
 *   snapshot/backup inclusion policies, and logs. It is NOT protection against
 *   a local attacker.
 *
 *   The run summary warns operators to treat this wallet as hot and to
 *   keep funds to the gas + rewards minimum. The real fix is OS-native secret
 *   storage (macOS Keychain, libsecret, Windows Credential Manager) or a
 *   hardware-backed signer; tracked as future work.
 */

import { readFileSync } from 'node:fs';
import { readKeystorePasswordFile } from '../earning/password-file.js';

/**
 * Resolve the file descriptor from `--password-fd <n>` or `--password-fd=<n>`.
 *
 * The first *usable* occurrence wins -- `resolveCliPassword` merges the verb
 * argv with `process.argv`, so the flag routinely appears twice. A present flag
 * with no usable occurrence throws: silently returning undefined fell through to
 * `JINN_PASSWORD` or the keystore-password file, decrypting with a different
 * secret than the operator supplied (#4375).
 */
export function parsePasswordFdFromArgv(argv: string[]): number | undefined {
  let seen = false;
  for (const [idx, arg] of argv.entries()) {
    let raw: string | undefined;
    if (arg === '--password-fd') {
      seen = true;
      raw = argv[idx + 1];
    } else if (arg.startsWith('--password-fd=')) {
      seen = true;
      raw = arg.slice('--password-fd='.length);
    } else {
      continue;
    }
    const n = raw ? parseInt(raw, 10) : NaN;
    if (Number.isFinite(n) && n >= 0) return n;
  }
  if (seen) {
    throw new Error(
      'Missing or invalid value for --password-fd (expected a non-negative file descriptor)',
    );
  }
  return undefined;
}

export function readPasswordFromFd(fd: number): string {
  const buf = readFileSync(fd, { encoding: 'utf8' });
  return buf.replace(/\r?\n$/, '').trim();
}

function mergeArgv(argv?: string[]): string[] {
  const fromVerb = argv ?? [];
  const fromProcess = typeof process !== 'undefined' ? process.argv.slice(2) : [];
  return [...fromVerb, ...fromProcess];
}

export type CliPasswordSource = 'fd' | 'env' | 'primary' | 'legacy';

export type ResolveCliPasswordOptions = {
  earningDir?: string;
};

export type ResolvedCliPassword =
  | { ok: true; password: string; source: CliPasswordSource; filePath?: string }
  | { ok: false; message: string };

export function resolveCliPassword(
  argv: string[] | undefined,
  env: NodeJS.ProcessEnv = process.env,
  options: ResolveCliPasswordOptions,
): ResolvedCliPassword {
  // 1. --password-fd wins (explicit scripted task).
  const merged = mergeArgv(argv);
  let fd: number | undefined;
  try {
    fd = parsePasswordFdFromArgv(merged);
  } catch (e) {
    return { ok: false, message: e instanceof Error ? e.message : String(e) };
  }
  if (fd !== undefined) {
    try {
      const password = readPasswordFromFd(fd);
      if (!password) {
        return { ok: false, message: 'Password from --password-fd is empty.' };
      }
      return { ok: true, password, source: 'fd' };
    } catch (e) {
      return {
        ok: false,
        message: e instanceof Error ? e.message : String(e),
      };
    }
  }

  // 2. JINN_PASSWORD env (explicit operator-set).
  const envPassword = env['JINN_PASSWORD'];
  if (envPassword) return { ok: true, password: envPassword, source: 'env' };

  // 3. Primary `<earningDir>/keystore-password`, then host-wide legacy file.
  const fromFile = readKeystorePasswordFile(options.earningDir, env);
  if (fromFile) {
    return { ok: true, password: fromFile.password, source: fromFile.source, filePath: fromFile.path };
  }

  return {
    ok: false,
    message:
      'No keystore password found. Set JINN_PASSWORD, pass --password-fd N, or run `jinn run` to auto-generate one.',
  };
}

export function resolveNewPassword(
  env: Record<string, string | undefined>,
): { ok: true; password: string } | { ok: false; message: string } {
  const newPass = env['JINN_NEW_PASSWORD'];
  if (newPass && newPass.length >= 8) return { ok: true, password: newPass };
  if (newPass && newPass.length < 8)
    return { ok: false, message: 'New password must be at least 8 characters.' };
  return {
    ok: false,
    message: 'Set JINN_NEW_PASSWORD environment variable with your new password (min 8 characters).',
  };
}
