import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { serializeCanonicalJson } from "@jinn-network/task-execution-protocol";
import { canonicalJsonBytes } from "./index.js";
import { buildRepositoryWorkProfile } from "./documents/repository-work-1.0.js";
import { sealTaskProfile } from "./task-profile/seal.js";

// Cross-tree parity (program §7.15/§7.1): profiles re-implements sealing locally, but its
// canonical bytes MUST be byte-identical to the TEP protocol sealer's for the same value.
// `task-execution-protocol` exports `serializeCanonicalJson` (its canonical-bytes helper), so
// the equivalence is asserted directly here rather than carried only by a pinned-digest comment.
describe("cross-tree sealer byte-compatibility (task-execution-protocol)", () => {
  it("produces identical canonical bytes to the TEP protocol sealer for the key-order-sensitive record", async () => {
    const value = JSON.parse(
      await readFile(new URL("../fixtures/equivalence/key-order-sensitive.json", import.meta.url), "utf8"),
    );
    expect(canonicalJsonBytes(value)).toEqual(serializeCanonicalJson(value));
  });
});

// Task 12: the sealed asset on disk is the source of truth for downstream consumers (design
// §14/§15 "regenerated by seal-documents.mjs") — this asserts it stays byte-identical to what the
// builder produces right now, not just that `yarn check:documents` was run at some point in the
// past.
describe("repository-work/1.0 sealed asset matches its builder (design §8)", () => {
  it("profile.json bytes equal sealTaskProfile(buildRepositoryWorkProfile()).bytes, and profile.sha256 pins the same digest", async () => {
    const sealed = sealTaskProfile(buildRepositoryWorkProfile());
    const onDiskBytes = await readFile(
      new URL("../profiles/task-profiles/repository-work/1.0/profile.json", import.meta.url),
    );
    expect(new Uint8Array(onDiskBytes)).toEqual(sealed.bytes);
    const pinned = (
      await readFile(
        new URL("../profiles/task-profiles/repository-work/1.0/profile.sha256", import.meta.url),
        "utf8",
      )
    ).trim();
    expect(pinned).toBe(sealed.digest);
  });
});
