import { describe, expect, it, vi } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { keccak256, recoverAddress } from 'viem';
import { SignedEnvelopeSchema } from '../../src/types/envelope.js';
import { canonicalJson } from '../../src/util/canonical-json.js';
import {
  assembleAndSignEnvelope,
  type EnvelopeInputs,
} from '../../src/harnesses/engine/envelope-assembly.js';

vi.mock('../../src/adapters/mech/ipfs.js', () => ({
  uploadToIpfs: vi.fn(async () => 'bafy-golden-envelope'),
}));

const ANVIL_KEY_0 = '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80' as const;
const ANVIL_ADDRESS_0 = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266' as const;

const goldenInputs: EnvelopeInputs = {
  solverType: 'prediction.v0',
  role: 'solution',
  generatedAt: 1750000000,
  task: {
    cid: 'bafybeigoldenenvelopefixture0000000000000000000000000000000',
    onchainCreationTx: `0x${'11'.repeat(32)}`,
    onchainCreationBlock: 1,
    requestId: `0x${'22'.repeat(32)}`,
  },
  participant: {
    safeAddress: `0x${'33'.repeat(20)}`,
    agentEoa: ANVIL_ADDRESS_0,
  },
  window: { startTs: 1749999000, endTs: 1750000000 },
  executor: {
    implName: 'golden-fixture',
    implVersion: '0.0.1',
    clientGitSha: '0000000000000000000000000000000000000000',
    codeDigest: `sha256:${'a'.repeat(64)}`,
    runtimeBundleDigest: `sha256:${'b'.repeat(64)}`,
    plugins: [],
    signingKey: { kind: 'agent-eoa', pubkey: ANVIL_ADDRESS_0 },
    mode: 'frozen',
  },
  evidenceTier: 'self-signed',
  attestation: null,
  trajectory: null,
  artifacts: [],
  payload: {
    prediction: {
      probability: '0.5',
      submittedAt: 1750000000,
      modelId: 'golden-fixture',
    },
  },
};

/**
 * Golden-envelope fixture test (#1832).
 *
 * The fixture is one canonical signed envelope with a pinned hash + signature,
 * produced once by `test/fixtures/regen-golden-envelope.ts` with the
 * well-known Anvil test key #0. It freezes the envelope seam four ways:
 *
 *   (a) the production envelope assembly + signing path must regenerate the
 *       fixture byte-for-byte;
 *   (b) the fixture still parses under SignedEnvelopeSchema — schema widening
 *       that breaks old envelopes fails here;
 *   (c) re-canonicalizing the envelope body (minus `signature`) reproduces the
 *       pinned keccak256 hash — any canonical-JSON drift fails here;
 *   (d) recovering the signer from (hash, sig) yields the fixture's signer —
 *       any signing-scheme drift fails here.
 *
 * If a deliberate schema/canonicalization change breaks this test, re-run the
 * regen script and review the fixture diff as part of the change.
 */
const fixturePath = fileURLToPath(
  new URL('./client-golden-envelope/golden-envelope.v0.json', import.meta.url),
);

describe('golden envelope fixture (#1832)', () => {
  const fixtureBytes = readFileSync(fixturePath, 'utf-8');
  const fixture = JSON.parse(fixtureBytes);

  it('is regenerated byte-for-byte by the production signing and assembly path', async () => {
    const { envelope } = await assembleAndSignEnvelope(goldenInputs, {
      ipfsRegistryUrl: 'http://unused.test',
      agentEoaPrivateKey: ANVIL_KEY_0,
    });

    expect(`${JSON.stringify(envelope, null, 2)}\n`).toBe(fixtureBytes);
    expect(canonicalJson(envelope)).toBe(canonicalJson(fixture));
  });

  it('parses under SignedEnvelopeSchema', () => {
    const parsed = SignedEnvelopeSchema.safeParse(fixture);
    expect(parsed.success, JSON.stringify(parsed.success ? '' : parsed.error.issues, null, 2)).toBe(true);
  });

  it('canonical hash of the envelope body matches the pinned signature.hash', () => {
    const { signature, ...unsigned } = fixture;
    const canonical = canonicalJson(unsigned);
    const hash = keccak256(new TextEncoder().encode(canonical));
    expect(hash).toBe(signature.hash);
  });

  it('signer recovered from (hash, sig) matches the pinned signature.signer', async () => {
    const { signature } = fixture;
    const recovered = await recoverAddress({
      hash: signature.hash,
      signature: signature.sig,
    });
    expect(recovered.toLowerCase()).toBe(signature.signer.toLowerCase());
  });
});
